HairSalon/Models/Client.cs
namespace HairSalon.Models
{
  public class Client
  {
    public int ClientId { get; set; }
    public string Name { get; set; }
    public string Appointment { get; set; }
    public string Notes { get; set; }
    public int StylistId { get; set; }
  }
}

HairSalon/Models/HairSalonContext.cs
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Models 
{
  public class HairSalonContext : DbContext 
  {
    public DbSet<Stylist> Stylists { get; set; } 
    public DbSet<Client> Clients { get; set; }
    public HairSalonContext(DbContextOptions options) : base(options) { } 
  }
}

HairSalon/Models/Stylist.cs
namespace HairSalon.Models 
{
  public class Stylist
  {
    public int StylistId { get; set; }
    public string Name { get; set; }
    public string StyleType { get; set; }
    public List<Client> Clients { get; set; }
  }
}

HairSalon/Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;

namespace HairSalon.Controllers
{
  public class ClientController : Controller 
  {
    private readonly HairSalonContext _db;

    public ClientController(HairSalonContext db)
    {
      _db = db;
    }

    [HttpGet("/client/details")]
    public ActionResult Details(string search)
    {
      List<Client> foundClients = _db.Clients
        .Where(client => client.Name.Contains(search))
        .ToList();
      List<Stylist> stylists = _db.Stylists.ToList();
      ViewBag.Stylists = stylists;
      return View(foundClients);
    }

    [HttpGet("/client/{id}/delete")]
    public ActionResult Delete(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      return View(thisClient);
    }

    [HttpGet("/client/{id}/edit")]
    public ActionResult Edit(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      return View(thisClient);
    }

    [HttpPost("client/{id}/create")]
    public ActionResult Create(int id, Client client)
    {
      client.StylistId = id;
      _db.Clients.Add(client);
      _db.SaveChanges();
      return Redirect($"/stylist/details/{id}");
    }

    [HttpPost("/client/{id}/delete/confirm")]
    public ActionResult DeleteConfirm(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      _db.Clients.Remove(thisClient);
      _db.SaveChanges();
      return Redirect($"/stylist/details/{thisClient.StylistId}");
    }

    [HttpPost("/client/{clientId}/stylist/{stylistId}/edit")]
    public ActionResult EditConfirm(int clientId, int stylistId, Client client)
    {
      client.ClientId = clientId;
      client.StylistId = stylistId;
      _db.Clients.Update(client);
      _db.SaveChanges();
      return Redirect($"/stylist/details/{stylistId}");
    }
  }
}

HairSalon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace HairSalon.Controllers 
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }

    }
}

HairSalon/Controllers/StylistController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;

namespace HairSalon.Controllers
{
  public class StylistController : Controller 
  {
    private readonly HairSalonContext _db;

    public StylistController(HairSalonContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      List<Stylist> model = _db.Stylists.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    public ActionResult Details(int id)
    {
      Stylist thisStylist = _db.Stylists
        .Include(stylist => stylist.Clients)
        .FirstOrDefault(stylist => stylist.StylistId == id);    
      List<Client> dbClients = _db.Clients.ToList();
      thisStylist.Clients = new List<Client> { };
      foreach (Client client in dbClients)
      {
        if (client.StylistId == thisStylist.StylistId)
        {
          thisStylist.Clients.Add(client);
        }
      }
      return View(thisStylist);
    }

    [HttpGet("/stylist/{id}/edit")]
    public ActionResult Edit(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    [HttpGet("/stylist/{id}/delete")]
    public ActionResult Delete(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    [HttpPost]
    public ActionResult Create(Stylist stylist)
    {
      _db.Add(stylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost("/stylist/{id}/delete/confirm")]
    public ActionResult DeleteConfirm(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      List<Client> stylistClients = _db.Clients.ToList();
      foreach (Client client in stylistClients)
      {
        if (client.StylistId == id)
        {
          _db.Clients.Remove(client);
        }
      }
      _db.Stylists.Remove(thisStylist);
      _db.SaveChanges();
      return Redirect("/stylist");
    }

    [HttpPost("/stylist/{id}/edit")]
    public ActionResult EditConfirm(int id, Stylist stylist)
    {
      stylist.StylistId = id;
      _db.Stylists.Update(stylist);
      _db.SaveChanges();
      return Redirect($"/stylist/details/{id}");
    }
  }
}

HairSalon/Views/Client/Delete.cshtml
@{
  Layout = "_Layout";
}

<h2 style="text-align: center;">Are you sure you want to delete <span id="delete">@Model.Name</span>?<h2>

    <form class="text-center" action="/client/@Model.ClientId/delete/confirm" method="post">
      <button class="btn btn-danger" type="submit">Delete Client</button>
      <a class="btn btn-warning" href="/stylist/details/@Model.StylistId">Cancel</a>
    </form>

HairSalon/Views/Client/Details.cshtml
@{
  Layout = "_Layout";
}
@using HairSalon.Models

@if (Model.Count == 0)
{
  <h1 class="text-center">No Clients found!</h1>
  <div class="text-center">
    <a class="btn btn-info" href="/stylist">Return to Stylists</a>
  </div>
}
else
{
  <div class="text-center mb-5">
    <a class="btn btn-info" href="/stylist">Return to Stylists</a>
  </div>
  @foreach (Client client in Model)
  {
    <div class="card text-center">
      <div class="card-body">
        @foreach (Stylist stylist in @ViewBag.Stylists)
        {
          if (@client.StylistId == stylist.StylistId)
          {
            <h1 class="card-title"><u>Stylist</u></h1>
            <h3 class="card-title">@Html.ActionLink($"{@stylist.Name}", "Details", "Stylist", new { id = @stylist.StylistId })
            </h3>
          }
        }
        <h1 class="card-title"><u>Client</u></h1>
        <h3 class="card-title">@client.Name</h3>
        <p class="card-text">@client.Appointment</p>
        <p class="card-text">@client.Notes</p>
        <a class="btn btn-danger w-25" href="/client/@client.ClientId/delete">Delete</a>
            <a class="btn btn-warning w-25" href="/client/@client.ClientId/edit">Edit</a>
      </div>
    </div>
  }
}

HairSalon/Views/Client/Edit.cshtml
@{
  Layout = "_Layout";
}

<h1 class="text-center">@Model.Name</h1>

<div class="form-group text-center w-25 m-auto">
  <form action="/client/@Model.ClientId/stylist/@Model.StylistId/edit" method="post">
    <label class="form-label" for="Name">Client Name:</label>
    <input class="form-control" type="text" name="Name" id="Name" value="@Model.Name">
    <br>
    <label class="form-label" for="Appointment">Appointment Date/Time:</label>
    <input class="form-control" type="text" name="Appointment" id="Appointment" value="@Model.Appointment">
    <br>
    <label class="form-label" for="Notes">Notes:</label>
    <input class="form-control" type="text" name="Notes" id="Notes" value="@Model.Notes">
    <br>
    <button class="form-control btn btn-success" type="submit">Edit Client</button>
    <a class="button btn btn-warning" href="/stylist/details/@Model.StylistId">Cancel</a>
  </form>
</div>

HairSalon/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1 class="text-center">Welcome to Eau Claire's Salon!</h1>

<div class="text-center">
<a class="btn btn-info w-25 mt-3" href="/stylist">See all Stylists</a>
<br>
<a class="btn btn-success w-25 mt-3" href="/stylist/create">Add new Stylist</a>
</div>

HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Eau Claire's Salon</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="~/css/styles.css">
</head>

<body>
  <div class="container">
    <div class="jumbotron">
      <h1 id="jumbotron">Eau Claire's Salon</h1>
    </div>
  @RenderBody()
  </div>
</body>

</html>

HairSalon/Views/Stylist/Create.cshtml
@{
  Layout = "_Layout";
}

<div class="form-group text-center w-25 m-auto">
  <form action="/stylist/create" method="post">
    <label class="form-label" for="Name">Stylist Name:</label>
    <input class="form-control" type="text" name="Name" id="Name">
    <br>
    <label class="form-label" for="StyleType">Service provided:</label>
    <input class="form-control" type="text" name="StyleType" id="StyleType">
    <br>
    <button class="form-control btn btn-success" type="submit">Add Stylist</button>
    <a class="button btn btn-info" href="/stylist">See all Stylists</a>
  </form>
</div>

HairSalon/Views/Stylist/Delete.cshtml
@{
  Layout = "_Layout";
}

<h2 style="text-align: center;">Are you sure you want to delete <span id="delete">@Model.Name</span>?<h2>

<form class="text-center" action="/stylist/@Model.StylistId/delete/confirm" method="post">
  <button class="btn btn-danger" type="submit">Delete Stylist</button>
  <a class="btn btn-warning" href="/stylist/details/@Model.StylistId">Cancel</a>
</form>

HairSalon/Views/Stylist/Details.cshtml
@{
  Layout = "_Layout";
}
@using HairSalon.Models;

<div class="row">
  <div class="col-6">
    <h1 class="text-center">@Model.Name</h1>
    <h5 class="text-center"><u>Style Type</u></h5>
    <p class="text-center">@Model.StyleType</p>

    @if (@Model.Clients.Count == 0)
    {
      <p class="text-center">No clients have been added yet!</p>
    }
    else
    {
      @foreach (Client client in Model.Clients)
      {
        <div class="card text-center">
          <div class="card-body">
            <h3 class="card-title">@client.Name</h3>
            <p class="card-text">@client.Appointment</p>
            <p class="card-text">@client.Notes</p>
            <a class="btn btn-danger w-25" href="/client/@client.ClientId/delete">Delete</a>
            <a class="btn btn-warning w-25" href="/client/@client.ClientId/edit">Edit</a>
          </div>
        </div>
      }
    }
  </div>
  <div class="col-2"></div>
  <div class="stick col-4">
    <div class="form-group">
      <form action="/client/@Model.StylistId/create" method="post">
        <label class="form-label" for="Name">Client Name:</label>
        <input class="form-control" type="text" name="Name" id="Name">
        <br>
        <label class="form-label" for="Appointment">Appointment Date/Time:</label>
        <input class="form-control" type="text" name="Appointment" id="Appointment">
        <br>
        <label class="form-label" for="Notes">Notes:</label>
        <input class="form-control" type="text" name="Notes" id="Notes">
        <br>
        <button class="form-control btn btn-success" type="submit">Add A Client</button>
        <a class="button btn btn-warning" href="/stylist/@Model.StylistId/edit">Edit Stylists</a>
        <a class="button btn btn-info" href="/stylist">See all Stylists</a>
        <a class="button btn btn-danger" href="/stylist/@Model.StylistId/delete">Delete Stylist</a>
      </form>
    </div>
  </div>
</div>

HairSalon/Views/Stylist/Edit.cshtml
@{
  Layout = "_Layout";
}  

<h1 class="text-center">@Model.Name</h1>

<div class="form-group text-center w-25 m-auto">
  <form action="/stylist/@Model.StylistId/edit" method="post">
    <label class="form-label" for="Name">Stylist Name:</label>
    <input class="form-control" type="text" name="Name" id="Name" value="@Model.Name">
    <br>
    <label class="form-label" for="StyleType">Service provided:</label>
    <input class="form-control" type="text" name="StyleType" id="StyleType" value="@Model.StyleType">
    <br>
    <button class="form-control btn btn-success" type="submit">Edit Stylist</button>
    <a class="button btn btn-warning" href="/stylist/details/@Model.StylistId">Cancel</a>
  </form>
</div>

HairSalon/Views/Stylist/Index.cshtml
@{
  Layout = "_Layout";
}
@using HairSalon.Models

<div class="row">
  <div class="col-6">
    <h1 class="text-center">Stylists</h1>

    @if (Model.Count == 0)
    {
      <p class="text-center">No stylist have been added yet!</p>
    }
    else 
    {
      <ul class="list-group mt-4">
        @foreach (Stylist stylist in Model)
        {
          <li class="list-group-item text-center w-75 m-auto">@Html.ActionLink($"{stylist.Name}", "Details", new { id = stylist.StylistId })</li>
        }
      </ul>
    }
    <div class="w-50 m-auto mt-3">
      <a class="button btn btn-success" href="/stylist/create">Add new Stylist</a>
    </div>
  </div>
  <div class="col-6">
    <form action="/client/details" method="get">
        <label class="form-label" for="search">Search for a client:</label>
        <input class="form-control" type="text" name="search" id="search">
        <br>
        <button class="form-control btn btn-primary" type="submit">Search</button>
      </form>
  </div>
</div>